// src/lib/components/ComposeForm.svelte
<script lang="ts">
	import type { ModelEntry } from '$lib/server/models/config';
	import { sendMessage } from '$lib/conversations.remote';

	let {
		conversationId,
		models,
		defaultModel,
		busy,
	}: {
		conversationId: string;
		models: ModelEntry[];
		defaultModel: string;
		busy: boolean;
	} = $props();

	let formEl: HTMLFormElement | null = $state(null);

	function onKeyDown(e: KeyboardEvent) {
		if (e.key !== 'Enter') return;
		if (e.shiftKey) return;
		if (busy) return;
		e.preventDefault();
		formEl?.requestSubmit();
	}
</script>

<!--
  Send-message form. Uses the `sendMessage` remote `form` so it works without
  JS (full-page POST + 303 redirect), and progressively enhances when JS is
  available — SvelteKit handles the network call and invalidates the page,
  causing the load function (and SSE re-subscription) to refresh state.
-->
<form
	bind:this={formEl}
	{...sendMessage.for(conversationId).enhance(async ({ form, submit }) => {
		await submit();
		form.reset();
		return;
	})}
	class="compose"
>
	<input type="hidden" name="conversationId" value={conversationId} />
	<textarea
		name="content"
		placeholder="Send a message…"
		required
		disabled={busy}
		rows={1}
		onkeydown={onKeyDown}
	></textarea>
	<div class="row">
		<select name="model" value={defaultModel} aria-label="Model">
			{#each models as m (m.slug)}
				<option value={m.slug}>{m.label}</option>
			{/each}
		</select>
		<button type="submit" class="send" disabled={busy} aria-label={busy ? 'Generating…' : 'Send'}>
			<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
				<line x1="12" y1="19" x2="12" y2="5" />
				<polyline points="5 12 12 5 19 12" />
			</svg>
		</button>
	</div>
</form>

// src/frontend/components/ComposeForm.tsx
import { useRef, type FormEvent, type KeyboardEvent } from 'react';
import type { ModelEntry } from '../../models/config';

export type ComposeFormProps = {
	conversationId: string;
	models: ModelEntry[];
	defaultModel: string;
	busy: boolean;
};

export function ComposeForm({ conversationId, models, defaultModel, busy }: ComposeFormProps) {
	const formRef = useRef<HTMLFormElement | null>(null);

	const onKeyDown = (e: KeyboardEvent<HTMLTextAreaElement>) => {
		// Enter submits, Shift-Enter inserts a newline. Cmd/Ctrl-Enter also submits.
		if (e.key !== 'Enter') return;
		if (e.shiftKey) return;
		if (busy) return;
		e.preventDefault();
		formRef.current?.requestSubmit();
	};

	const onSubmit = (e: FormEvent<HTMLFormElement>) => {
		// Don't gate the native submit when busy; the disabled button already
		// covers that path. This handler exists so future client-side enhancements
		// (optimistic updates, etc.) can hook in.
		if (busy) e.preventDefault();
	};

	return (
		<form ref={formRef} className="compose" action={`/c/${conversationId}/messages`} method="post" onSubmit={onSubmit}>
			<textarea
				name="content"
				placeholder="Send a message…"
				required
				disabled={busy}
				rows={1}
				onKeyDown={onKeyDown}
			/>
			<div className="row">
				<select name="model" defaultValue={defaultModel} aria-label="Model">
					{models.map((m) => (
						<option key={m.slug} value={m.slug}>
							{m.label}
						</option>
					))}
				</select>
				<button type="submit" className="send" disabled={busy} aria-label={busy ? 'Generating…' : 'Send'}>
					<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
						<line x1="12" y1="19" x2="12" y2="5" />
						<polyline points="5 12 12 5 19 12" />
					</svg>
				</button>
			</div>
		</form>
	);
}
