// src/lib/components/ToolCall.svelte
<script lang="ts">
	import type { ToolCallRecord, ToolResultRecord } from '$lib/types/conversation';

	let {
		call,
		result,
		defaultOpen = false,
		nested = false,
	}: {
		call: ToolCallRecord;
		result?: ToolResultRecord;
		defaultOpen?: boolean;
		nested?: boolean;
	} = $props();

	const pending = $derived(!result);
	const open = $derived(pending || defaultOpen);
</script>

<details class="tool-call{nested ? ' nested' : ''}" data-tool-name={call.name} {open}>
	<summary>
		<span class="tool-call-name">{call.name}</span>
		{#if pending}
			<span class="tool-call-status pending">
				running<span class="streaming-indicator" aria-hidden="true">●</span>
			</span>
		{:else if result?.isError}
			<span class="tool-call-status error">error</span>
		{:else}
			<span class="tool-call-status ok">done</span>
		{/if}
	</summary>
	<div class="tool-call-body">
		<div class="tool-call-input">
			<div class="tool-call-label">Input</div>
			<pre><code>{JSON.stringify(call.input ?? {}, null, 2)}</code></pre>
		</div>
		{#if result}
			<div class="tool-call-result">
				<div class="tool-call-label">Result</div>
				<pre><code>{result.content}</code></pre>
			</div>
		{:else}
			<div class="tool-call-result pending">running…</div>
		{/if}
	</div>
</details>

// src/frontend/components/ToolCall.tsx
import type { ToolCallRecord, ToolResultRecord } from '../../types/conversation';

export function ToolCallCard({
	call,
	result,
	defaultOpen = false,
	nested = false,
}: {
	call: ToolCallRecord;
	result?: ToolResultRecord;
	defaultOpen?: boolean;
	nested?: boolean;
}) {
	const pending = !result;
	const open = pending || defaultOpen;
	return (
		<details className={`tool-call${nested ? ' nested' : ''}`} data-tool-name={call.name} open={open}>
			<summary>
				<span className="tool-call-name">{call.name}</span>
				{pending ? (
					<span className="tool-call-status pending">
						running<span className="streaming-indicator" aria-hidden="true">●</span>
					</span>
				) : result.isError ? (
					<span className="tool-call-status error">error</span>
				) : (
					<span className="tool-call-status ok">done</span>
				)}
			</summary>
			<div className="tool-call-body">
				<div className="tool-call-input">
					<div className="tool-call-label">Input</div>
					<pre>
						<code>{JSON.stringify(call.input ?? {}, null, 2)}</code>
					</pre>
				</div>
				{result ? (
					<div className="tool-call-result">
						<div className="tool-call-label">Result</div>
						<pre>
							<code>{result.content}</code>
						</pre>
					</div>
				) : (
					<div className="tool-call-result pending">running…</div>
				)}
			</div>
		</details>
	);
}
